server:
  port: 28081
#  address: 0.0.0.0
#  servlet:
#    context-path: /order-service

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/tcc_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz@WSX


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#Ribbon的负载均衡策略
ribbon:
  NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer : 0
  MaxAutoRetries: 0
  ReadTimeout: 3000
feign:
  hystrix:
    enabled : false
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
